### ISSUE TITLE
(Version 4.3.0)TouchID.isSupported() returns "TouchID" even when there is no fingerprints available

### ISSUE THREAD

**Issue by ronilitman** [naoufal/react-native-touch-id#171] opened 2018-10-28 11:06 UTC
Checked on IOS.
Till now it worked perfectly on the version I was using(4.1.0), but now on simulator and on a real device that has no fingerprints TouchID.isSupported() returns "TouchID", even though it should return false/undefined.

**Comment by zibs** [comment] 2018-10-28 17:47
Maybe take a look at this line - https://github.com/naoufal/react-native-touch-id/commit/51ede1dfd5b3ef3987dc28d856d823a0178549dc#diff-7b319858b5c7e6cc6467bc158c09176aR14 - could that have affected it?

**Comment by philolo1** [comment] 2018-10-30 11:17
@zibs @ronilitman  LAPolicyDeviceOwnerAuthentication will be also true if there is just a passcode support, i think we should delete this check. But how will passcodes be handled in generally. Maybe the api needs to be changed?

**Comment by zibs** [comment] 2018-10-30 15:11
Right, it's probably returning "TouchID" because the user has a passcode setup, and if they do, then you can use the authenticate method by passing the `passwordFallback` param as true

**Comment by philolo1** [comment] 2018-10-30 16:32
@zibs i think in isSupported it should not return "TouchID" but rather "Passcode". What do you think? it should be an easy pr to change that line of code.

**Comment by zibs** [comment] 2018-11-04 00:04
Feel free to make a PR!

**Comment by davidmarinangeli** [comment] 2018-11-08 14:40
Has anyone done that? If not, I could PR that. 😄

**Comment by philolo1** [comment] 2018-11-08 15:31
@davidmarinangeli i think it depends on what the behaviour should be? Should it be "Passcode" or should we rather just return false. Because really TouchID is not supported.

**Comment by davidmarinangeli** [comment] 2018-11-08 20:37
I think both are okay: I just wanted to find a way to make it work and split the cases (the _real_ TouchID supported and the _fake_ one).

**Comment by ben-snaize** [comment] 2018-11-09 09:40
Could do with this fix - it's also making devices that don't have Touch ID enabled return with a result of `'TouchID'` when calling `isSupported`

**Comment by philolo1** [comment] 2018-11-09 12:37
@ben-snaize @davidmarinangeli  i just made a pullrequest to return "Passcode", if passcode is available. https://github.com/naoufal/react-native-touch-id/pull/176.

**Comment by tlow92** [comment] 2018-11-09 13:11
I was using passcodes for a year with this library, without any problems. isSupported should still return LAErrorTouchIDNotEnrolled when no fingers are configured for Touch ID no matter if passcode is set or not. The latest changes mentioned above actually broke the code

**Comment by philolo1** [comment] 2018-11-09 13:13
ok @tlow92 i think it makes more sense to do it this way, i will update my pull request.

**Comment by davidmarinangeli** [comment] 2018-11-09 13:17
I've found a bug for iPads too: the "_isSupported()_" always returns false. Is that for the same reason? 🤔

**Comment by philolo1** [comment] 2018-11-09 13:19
i dont believe so. i changed my pull request just to ignore the passcode for now. 
https://github.com/naoufal/react-native-touch-id/pull/177

**Comment by tlow92** [comment] 2018-11-09 13:28
@philolo1 Thanks for the effort
In case someone is interested latest stable version is 4.1.0
So for production use reverting to that is probably safest bet

**Comment by zibs** [comment] 2018-11-09 16:51
@tlow92 @philolo1 Actually I think the direction we want to move in is to better support passcodes, and to do so, we should integrate your PR which returns "Passcode", if TouchId/FaceId are not supported, but passcode is.

**Comment by davidmarinangeli** [comment] 2018-11-09 17:05
Okay @zibs but can you confirm that for now the 4.1.0 is the best for production use?

**Comment by zibs** [comment] 2018-11-11 18:57
@ronilitman @tlow92 after thinking about it, I think you're correct. We will make it so that if TouchID/FaceID are not supported, isSupported will return an error.

However, since this library provides support for attempting to use passcodeFallback, the user can still attempt to call `authenticate` even if isSupported returns false.

Alternatively, we can add an option to `isSupported` that could be like `checkForPasscodeToo` (better name needed) and then if it's present, check to see if passcode is supported as well. That might be ideal for those wanting to always use the passcode fallback.

**Comment by tonmanayo** [comment] 2018-11-14 05:09
I rolled back to 4.1.1, seem to get the correct behaviour there

**Comment by dgreenehy** [comment] 2018-12-06 23:35
It's great to know if the device supports a particular biotype, but it also needs to have a way to let us know if the user has enrolled.  We may need to roll back as well as 4.3 is a breaking change for us.

**Comment by zibs** [comment] 2018-12-10 16:33
Yeah I think we'll have to make some changes here. It sounds like we should keep existing functionality of isSupported to return what it always returned, and then add a separate method to check if passcode is enabled.

**Comment by dgreenehy** [comment] 2018-12-12 16:16
The fix for this could potentially be exposing 2 methods, isSupported() and isEnrolled().  IsSupported() could return finger/face/passcode and isEnrolled() could simply return a boolean.

**Comment by zibs** [comment] 2018-12-12 19:16
I think that's the best solution @dgreenehy - can you make a PR? I probably can't get to anything until the holidays myself - sorry all!

**Comment by dgreenehy** [comment] 2018-12-12 22:42
@zibs Thanks for the reply, I am going to fork your repo and make the changes we need, once everything is working as intended I will get a PR to you.  Happy Holidays!

**Comment by zibs** [comment] 2019-02-15 19:19
4.4.0 should fix this regression by allowing a new config var passed into isSupported to return an error if faceid/touch id are not supported. please refer to the readme and the changelog!

**Closed by zibs** 2019-02-15 19:19 UTC

**Comment by abury** [comment] 2019-03-04 01:02
Is this still the case? Testing on a simulator that isn't enrolled in touch ID, I'm calling `isSupported` and it's returning "TouchID" 🤔

```javascript
  componentDidMount() {
    const optionalConfigObject = {
      unifiedErrors: false,
      passcodeFallback: true
    };
    TouchID.isSupported(optionalConfigObject)
      .then(biometryType => {
        console.log({ biometryType });
        // Success code
        if (biometryType === 'FaceID') {
          this.setState({ authenticationType: AUTHENTICATION_TYPES.FACE_ID });
        } else {
          this.setState({ authenticationType: AUTHENTICATION_TYPES.TOUCH_ID });
        }
      })
      .catch(error => {
        console.log({ error });
        this.setState({ authenticationType: AUTHENTICATION_TYPES.PASSCODE });
      });
  }
```

console.log:
```
Object {biometryType: "TouchID"}
```

Version: react-native-touch-id@^4.4.1:
Confirmed simulator is not enrolled in touch ID

**Comment by davidmarinangeli** [comment] 2019-03-04 09:00
Have you tried to downgrade the version to the ones we recommended?

**Comment by abury** [comment] 2019-03-04 19:39
@davidmarinangeli Thanks for the reply. I've tried it on:
* 4.4.1
* 4.1.1
* 4.1.0

None of these versions seem to be working for me, they all report TouchID regardless of enrollment.

**Comment by abury** [comment] 2019-03-04 20:42
I've found the issue. Looking at `TouchID.m`, the default value for `authenticationType` is true:

```
NSNumber *passcodeFallback = [NSNumber numberWithBool:true];
    if (RCTNilIfNull([options objectForKey:@"passcodeFallback"]) != nil) {
        passcodeFallback = [RCTConvert NSNumber:options[@"passcodeFallback"]];
    }
```

Also, it will only pass an error if `false` is passed:

```
    } else if ([passcodeFallback boolValue] && [context canEvaluatePolicy:LAPolicyDeviceOwnerAuthentication error:&error]) {
        // Attempt Authentification
        [context evaluatePolicy:LAPolicyDeviceOwnerAuthentication
                localizedReason:reason
                          reply:^(BOOL success, NSError *error)
         {
             [self handleAttemptToUseDeviceIDWithSuccess:success error:error callback:callback];
         }];
    }
```

The Readme says that `false` is the default value, and passing `true` will return an error, both of which are incorrect.

```javascript
const optionalConfigObject = {
  unifiedErrors: false // use unified error messages (default false)
  passcodeFallback: false // if true is passed, itwill allow isSupported to return an error if the device is not enrolled in touch id/face id etc. Otherwise, it will just tell you what method is supported, even if the user is not enrolled.  (default false)
}
```

Once I passed `false`, I got the desired behaviour. 

@zibs I'm happy to issue a PR to fix either the readme or the obj-c logic. 👍

**Comment by saadmutahar** [comment] 2022-02-16 05:54
Thanks @abury for saving my day
and yes this is true that isSupported return an error if **passcodeFallback is false**
