### ISSUE TITLE
Android crashes when authentication fails at second time

### ISSUE THREAD

**Issue by renanpupin** [naoufal/react-native-touch-id#67] opened 2018-01-17 21:25 UTC
It seems that android still keep the Fingerprint working after the first authentication.

`
ERROR: RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
`

TEST: Loop until authentication() returns true, at the second time this will crash.

```js
async validateTouchId(){
        let isAuthOk = false;
        while(!isAuthOk){

            try{
                let responseAuth = await TouchID.authenticate('Authentication');

                if(responseAuth){
                    isAuthOk = true;
                    return true;
                }else{
                    throw responseAuth;
                }

            } catch (e){
                console.log("Error",e);

                let successPromise = await new Promise((resolve, reject) => {
                    Alert.alert(
                        'Auth',
                        "Auth again.",
                        [
                            {text: 'Login again', onPress: () => {
                                    resolve(false);
                                }},
                            {text: 'Try again', onPress: async () => {
                                    resolve(true);
                                }},
                        ]
                    );
                });

                if(!successPromise){
                    return false;
                }
            }
        }
    }
```

**Comment by agustinaliagac** [comment] 2018-01-18 14:29
Same here ! Reproducing this bug on physical devices and emulators as well.

**Comment by agustinaliagac** [comment] 2018-01-18 15:05
It looks like the native Callback implementation only allows invoking it once: 
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/CallbackImpl.java

**Comment by zibs** [comment] 2018-01-27 16:36
Thanks for reporting this issue!

I can take a look in the coming days/weeks for a workaround - in the meantime feel free to open a PR if this is breaking for you!

**Comment by indieocean** [comment] 2018-02-01 14:24
Yeah we fixed this issue using promises since there is a mix of callbacks and promises it falls into the multiple callback issue. While using promises you don't have this issue since you don't send any more callback to native.

**Comment by marcorm** [comment] 2018-02-19 10:01
Hi @indieocean , could you please share what you've done? Thanks a lot!

**Comment by zibs** [comment] 2018-02-26 04:37
Master has a fix for this now, but is not yet released. will be bumped soon

**Closed** 2018-02-26 04:38 UTC
Labels: bug

**Comment by MikhailSemichev** [comment] 2018-03-03 05:58
Guys, could anyone consult when npm release with this bug fix will be shipped? Current release version is 4.0.0 and we are waiting for 4.x.x with the fixes. Thanks in advance.

**Comment by zibs** [comment] 2018-03-03 06:19
Yep any day now.

**Comment by ycb0318** [comment] 2018-03-07 09:29
I also have this problem yet，Did not solve it?

**Comment by zibs** [comment] 2018-06-30 18:59
@ycb0318 This has been out for a while in 4.0.1+

**Comment by johakr** [comment] 2018-07-26 11:05
@naoufal Please reopen this issue since it's still happening in 4.0.4 on android.

**Comment by zibs** [comment] 2018-07-26 14:31
@johakr Can you post any more details about what's happening for you. I can't reproduce on latest.

**Comment by johakr** [comment] 2018-07-30 07:49
@zibs 

`java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
    at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:28)
    at com.rnfingerprint.DialogResultHandler.onError(DialogResultHandler.java:22)
    at com.rnfingerprint.FingerprintDialog.onError(FingerprintDialog.java:147)
    at com.rnfingerprint.FingerprintHandler.onAuthenticationFailed(FingerprintHandler.java:43)
    at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedFailed(FingerprintManager.java:1320)
    at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:1227)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`
