### ISSUE TITLE
Package not compatible with React Native 0.56 (Android)

### ISSUE THREAD

**Issue by taranda** [naoufal/react-native-touch-id#138] opened 2018-07-09 15:22 UTC
This package will not compile with React Native 0.56.  The following error occurs when running `react-native run android`:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-touch-id'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-touch-id'. Minimum required is 25.0.0
```

Due to Google's [mandate](https://developer.android.com/distribute/best-practices/develop/target-sdk) that all new apps must target API 26 in order to be published on Google Play after 1 August 2018, React Native updated its build tools and target API.  This is causing many React Native packages to break.

Here are a couple of solutions  proposed in other packages:

- [PR for react-native-config](https://github.com/luggit/react-native-config/pull/248)
- [PR for react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen)
- [build.gradle for react-native-device-info](https://github.com/rebeccahughes/react-native-device-info/blob/master/android/build.gradle)

**Comment by zibs** [comment] 2018-07-10 03:05
Nice, @taranda thanks for the heads up! Do you want to make a PR for this? Otherwise I can get to it later this week

**Comment by taranda** [comment] 2018-07-10 14:37
I would, but I am not an Android developer.  I can copy one of the other PRs but I would not be confident in testing them.

**Comment by ErrorPro** [comment] 2018-07-12 13:12
@taranda Please try to make a PR.

**Comment by ErrorPro** [comment] 2018-07-12 13:36
Last RN uses `classpath 'com.android.tools.build:gradle:2.3.3'`, I tried to replace this line in the react-native-touch-id package and it worked.

**Comment by ErrorPro** [comment] 2018-07-12 13:58
I tried to update build.gradle to use the one RN uses `com.android.tools.build:gradle:2.3.3`. The error still presents.

**Comment by iscriptology** [comment] 2018-08-07 09:29
Hey guys any plan to release a new version with this fix?
Thanks.

**Comment by mkhazov** [comment] 2018-08-07 13:31
This can be fixed by specifying `compileSdkVersion` in your project's `build.gradle`: https://stackoverflow.com/a/25736483/1300562

**Comment by andreialecu** [comment] 2018-09-14 09:49
#140 was finally merged and this has been fixed looks like.

**Comment by zibs** [comment] 2018-09-21 03:01
4.0.5 is out - I'm going to close this if it's fixed! I'll re-open if it's not.

**Closed by zibs** 2018-09-21 03:01 UTC

**Comment by andreialecu** [comment] 2018-09-21 15:28
I can confirm that it is fixed for me.
